spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: husik927@gmail.com
    password: canpast92@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true